
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 1

[scrolling]
history = 2000

[window]
dynamic_padding = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 16
y = 16

[general]
import = [
  "~/.config/alacritty/one_dark.toml"
]
